services:
  test-task:
    container_name: test-task
    environment:
      - STORAGE_ADDR=postgres
    build:
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    ports:
      - "4000:4000"

  postgres:
    image: postgres:14.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "test"
      PGDATA: /data/postgres
    volumes:
       - ~/go-test-task:/data/postgres